##-- #/_docs



################################################################################

#! d f ml? .
#!   file:///C:/more/index/tmp/_/more/book/index.html

#! d s ml? -a
#! d s ml? -c
#! d s ml? -w _l
#! d s ml? -i .

#! mdbook --version
#! mdbook serve -d tmp/_/more/book
#!   localhost:3000
#! mdbook build -d tmp/_/more/book
#!   file:///C:/more/index/tmp/_/more/book/index.html

################################################################################

#! <:>
#! {
#!   ".": "index.ignore!i.ignore",
#!   "#": "#"
#! }
#! //
#! __$$ = function({ ...vars }) {
#!   const { $2 } = vars;
#!   
#!   if (false) {
#!   } else if ($2 === '_') {
#!     __$['#_._'](`mdbook watch -d tmp/_/more/book`);
#!   } else if ($2 === '.') {
#!     __$['#_.'](`mdbook build -d tmp/_/more/book`);
#!   } else if (true) {
#!   }
#! }
#! </:>

################################################################################



##-- #/_deps



################################################################################

[book]
authors = []
language = "en"
multilingual = false
src = "docs"

#[output.html.fold]
#enable = true
#level = 0

[output.html]
no-section-label = true
additional-css = ["docs/more/styles.css"]
additional-js = ["docs/more/script.js"]

################################################################################



##-- $:.json
#! {
#!   ".": [],
#!   ":": [],
#!   "?": [],
#!   "_": [],
#!   "#": "#"
#! }
##-- _tl:.json
#! [
#!   "#"
#! ]
##-- _m:.json
#! [
#!   "do/mo/scr!",
#!   "do/mo/sty!",
#!   "#"
#! ]
##-- _:book.toml.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs.json
#! {
#!   "/": true,
#!   "!": false,
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/index.md.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/more.json
#! {
#!   "/": true,
#!   "!": false,
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/more/_pres.md.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/more/_tmpl.md.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/more/script.js.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/more/styles.css.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/notes.json
#! {
#!   "/": true,
#!   "!": false,
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/notes/index.md.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _:docs/SUMMARY.md.json
#! {
#!   "/": false,
#!   "!": "x.s",
#!   "?": [],
#!   "#": "#"
#! }
##-- _tmpl:index
#! 
#! 
#! 
#! #############################################################################
#! 
#! <:_tmpl>
#! {
#!   "%": "",
#!   ".": [],
#!   ":": [],
#!   "!": [],
#!   "~": [],
#!   "?": [],
#!   "#": "#"
#! }
#! //
#! </:_tmpl>
#! 
#! #############################################################################
#! 
#! 
#! 
